### ISSUE TITLE
Save requirements.txt as a markdown document (.md)

### ISSUE THREAD

**Issue by shivanshsharma8834** [sksarvesh007/image-sharpening-and-blurring#1]

**Comment by sksarvesh007** [comment]
the requirements.txt is autogenerated using the python -m pipreqs.pipreqs command  , i will look if the requirements file in the txt format causes any issues or not

**Comment by Sama-004** [comment]
> the requirements.txt is autogenerated using the python -m pipreqs.pipreqs command , i will look if the requirements file in the txt format causes any issues or not

axa

**Comment by sksarvesh007** [comment]
:lainah:
